- op: replace
  path: /spec
  value:
    rules:
      - host: demo-app-zerok-spill.getanton.com
        http:
          paths:
          - backend:
              service:
                name: svc-app-zerok-spill
                port: 
                  number: 80
            path: /.*
            pathType: Prefix