apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-test
  labels:
    dep: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-hpa
  minReplicas: 4
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: "fire_controller_gauge"
        selector:
          matchLabels:
            resource.labels.namespace: "zerok_controller"
      target:
        type: AverageValue
        value: "100"


# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: hpa-test
#   labels:
#     dep: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: dep-hpa
#   minReplicas: 4
#   maxReplicas: 10
#   - type: External
#     external:
#       metric:
#         name: "fire_gauge_external"
#         selector:
#           matchLabels:
#             resource.labels.namespace: "zerok_controller"
#       target:
#         type: AverageValue
#         value: "100"

  # - type: Pods
  #   pods:
  #     metricName: fire_gauge_max
  #     targetAverageValue: "100"



  # - type: Object
  #   object:
  #     metric:
  #       name: requests-per-second
  #     describedObject:
  #       apiVersion: networking.k8s.io/v1
  #       kind: Ingress
  #       name: ing-app-hpa
  #     target:
  #       type: Value
  #       value: 50

  # - type: Pods
  #   pods:
  #     metricName: myapplication_api_response_time_avg
  #     targetAverageValue: "500"

  # - type: Pods
  #   pods:
  #     metric:
  #       name: custom_prometheus
  #     target:
  #       type: AverageValue
  #       averageValue: 20