apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
  labels:
    app: myapp
    dep: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
      dep: default
  template:
    metadata:
      annotations:
        prometheus.io/path: "/status/format/prometheus"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: myapp
        dep: default
