{
 "title": "ZeroK Demo",
 "time": { "from": "2022-10-28T09:52:01.103Z", "to": "2022-10-28T10:06:29.048Z" },
 "templating": {
  "list": [
   {
    "name": "namespace1",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "namespace2",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "demoStage",
    "label": "Demo Stage",
    "query": "Evaluate Concurrency, Rate Limit"
   },
   {
    "name": "soakpod",
    "label": "Soak pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"zerok\"}, pod)"
    }
   },
   {
    "name": "spillpod",
    "label": "Spill pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"zerok\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 19, "x": 0, "y": 1 },
     "options": {
      "content": "\n\n<br>\n  <a \n     href=\"http://demo-load-generator.getanton.com/status/zk_soak\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"soak\">\n  🪵 soak</a>\n\n  <a \n     href=\"http://demo-load-generator.getanton.com/status/zk_spill\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"spill\">\n  🪵 spill</a>\n\n  <a \n     href=\"http://demo-load-generator.getanton.com/status/app\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"app\">\n  🪵 app</a>\n  <a \n     href=\"http://demo-load-generator.getanton.com/reset\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"Reset the state\">\n  🔂</a>\n<!--\n<a \nhref=\"https://aax7mshw45.execute-api.us-east-2.amazonaws.com/default/shutdown\"  \ntarget=\"_blank\"\nstyle=\"\nborder-radius: 7px; \nmargin: 0.25rem 0.30rem; \nborder: 1px solid;\ntext-decoration: none; \npadding: 1rem 1.5rem; \nwidth: 100px;\nline-height: 100px;\nfont-size: 36px;\ntext-align: center\"\ntitle=\"Kill demo machines\">\n🔥</a>\n-->"
     }
    }
   ]
  },
  { "title": "Stage 1 - Concurrency Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 2 },
   "options": {
    "content": "# Concurrency Test\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "options": {
    "content": "<br/>\n<a\n   href=\"#\"\n   onclick=\"\n   \twindow.open('http://demo-load-generator.getanton.com/start-concurrency-test?vus=300&mvus=300&timeunit=1m&ssoak=2m_640-2m_920-1m_600-1m_600-1m_840-1m_840-1m_680-2m_760&sspill=2m_640-2m_360-1m_680-1m_680-1m_440-1m_440-1m_600-2m_520', '_blank', 'toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=500,width=400,height=400');\n      window.open('http://demo-load-generator.getanton.com/start/app?vus=200&mvus=200&rate=1800&stages=2m_220-6m_220&timeunit=1m', '_blank', 'toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=100,width=400,height=400');\"\n   style=\"\n      border-radius: 7px; \n      margin: 0.25rem; \n      border: 1px solid;\n      text-decoration: none; \n      cursor: pointer;\n      padding: 1rem 1.5rem; \n      width: 100px;\n      line-height: 10px;\n      font-size: 36px;\n      text-align: center;\"\n   >\n▶️\n</a>\n"
   }
  },
  {
   "title": "Pod count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "4", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod count (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "4", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Soak Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spill Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request count -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate(k6_http_reqs{scenario=~\"app_.*\"}[$__rate_interval]) * 60)",
     "legendFormat": "Service"
    },
    {
     "expr": "sum (rate(k6_http_reqs{scenario=~\"app_.*\"}[$__rate_interval]) * 60) / 4",
     "legendFormat": "Per Pod"
    }
   ]
  },
  {
   "title": "Request count [zerok-soak] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate(k6_http_reqs{scenario=~\"zk_soak.*\"}[$__rate_interval])) * 60",
     "legendFormat": "soak"
    },
    {
     "expr": "sum (rate(k6_http_reqs{scenario=~\"zk_spill.*\"}[$__rate_interval])) * 60",
     "legendFormat": "spill"
    }
   ]
  },
  {
   "title": "Latency - $namespace1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(k6_custom_duration_avg{scenario=~\"app_.*\"})",
     "legendFormat": "app"
    }
   ]
  },
  {
   "title": "Latency - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (k6_custom_duration_avg{scenario=~\"zk_spill_.*\"})",
     "legendFormat": "spill"
    },
    {
     "expr": "sum (k6_custom_duration_avg{scenario=~\"zk_soak_.*\"})",
     "legendFormat": "soak"
    }
   ]
  },
  {
   "title": "Max concurrent request count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max concurrent request count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_stageGauge{scenario=~\"zk.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error count [app] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"app_.*\", status!=\"200\"}[$__rate_interval])) * 60",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Error count [zerok-soak] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"zk.*\", status!=\"200\"}[$__rate_interval])) * 60",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  { "title": "Quality Of service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 37 },
   "options": {
    "content": "\n<br>\n  <a \n     href=\"http://demo-load-generator.getanton.com/start/app?vus=200&mvus=200&rate=1800&stages=2m_3600-6m_3600&timeunit=1m\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 10px;\n            font-size: 36px;\n            text-align: center;\"\n     title=\"Run test\">\n  ▶️ App </a>\n\n   <a \n   href=\"http://demo-load-generator.getanton.com/start/zk?vus=200&mvus=200&rate=1800&stages=2m_3600-3m_3600_80-3m_3600_90&timeunit=1m\"\n   target=\"_blank\"\n   style=\"\n         border-radius: 7px; \n         margin: 0.25rem; \n         border: 1px solid;\n         text-decoration: none; \n         padding: 1rem 1.5rem; \n         width: 100px;\n         line-height: 10px;\n         font-size: 36px;\n         text-align: center;\"\n   title=\"Run test\">\n▶️ ZK</a>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 37 },
   "options": {
    "content": "\n<br>\n  <a \n     href=\"http://demo-load-generator.getanton.com/start/app?vus=200&mvus=200&rate=1800&stages=2m_3600-6m_3600&timeunit=1m\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 10px;\n            font-size: 36px;\n            text-align: center;\"\n     title=\"Run test\">\n  ▶️ QOS: Rate limit non essencial AP! </a>\n <p />\n   <a \n   href=\"http://demo-load-generator.getanton.com/start/zk?vus=200&mvus=200&rate=1800&stages=2m_3600-3m_3600_80-3m_3600_90&timeunit=1m\"\n   target=\"_blank\"\n   style=\"\n         border-radius: 7px; \n         margin: 0.25rem; \n         border: 1px solid;\n         text-decoration: none; \n         padding: 1rem 1.5rem; \n         width: 100px;\n         line-height: 10px;\n         font-size: 36px;\n         text-align: center;\"\n   title=\"Run test\">\n▶️ ZK</a>\n"
   }
  },
  {
   "title": "Request count -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"app_.*\"}[$__rate_interval]) * 60) / 4",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Request count [zerok-soak] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"zk.*\", status=\"200\"}[$__rate_interval])) * 60",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Latency - $namespace1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(scenario) (k6_custom_app_checkout_duration_avg)",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "sum by(scenario) (k6_custom_app_coupons_duration_avg)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Latency - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(scenario) (k6_custom_zk_checkout_duration_avg)",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "sum by(scenario) (k6_custom_zk_spill_checkout_duration_avg)",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "sum by(scenario) (k6_custom_zk_soak_checkout_duration_avg)",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "sum by(scenario) (k6_custom_zk_coupons_duration_avg)",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "sum by(scenario) (k6_custom_zk_spill_coupons_duration_avg)",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "sum by(scenario) (k6_custom_zk_soak_coupons_duration_avg)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Error count [app] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"app_.*\", status!=\"200\"}[$__rate_interval])) * 60",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Error count [zerok-soak] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"zk.*\", status!=\"200\"}[$__rate_interval])) * 60",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  { "title": "CPU charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "CPU Usage per Pod (limit) - $namespace1",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace1\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace1\"}) by (pod)) * 100  ",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "CPU Usage per Pod (limit) - $namespace1",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace1\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace1\"}) by (pod)) * 100  ",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "CPU Usage per Pod (limit) - $namespace2 - soak",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace2\", pod=\"$soakpod\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace2\", pod=\"$soakpod\"}) by (pod)) * 100  ",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "CPU Usage per Pod - $namespace2 - spill",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace2\", pod=\"$spillpod\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace2\", pod=\"$spillpod\"}) by (pod)) * 100  ",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "CPU Usage : $namespace1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace1\"}) by (namespace) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Usage : $namespace1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\", pod=~\"$soakpod|$spillpod\"}) * 1000\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace2\", pod=~\"$soakpod|$spillpod\"}) by (namespace) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\", pod=~\"$soakpod|$spillpod\"}) * 1000\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "Memory charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod - $namespace1",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace1\", container!=\"\", image!=\"\"} / 1000000) by (pod)",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Memory Usage per Pod - $namespace2",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\", container!=\"\", image!=\"\"} / 1000000) by (pod)",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Memory Utilization - $namespace1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace1\", container!=\"POD\", image!=\"\"})",
       "legendFormat": "Memory Utilization"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"memory\"}\n)\n",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"memory\"}\n)\n",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Memory Utilization - $namespace2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\", container!=\"POD\", image!=\"\"})",
       "legendFormat": "Memory Utilization"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"}\n)\n",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"}\n)\n",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  }
 ]
}