{
 "title": "Load-test Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) * 1000",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", resource=\"cpu\"}\n) * 1000\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", container!=\"POD\", image!=\"\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(kube_pod_info{namespace=~\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"POD\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) * 1000"
    },
    {
     "expr": "sum(label_replace(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) *1000"
    },
    {
     "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) / sum(label_replace(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) *1000"
    },
    {
     "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) / sum(label_replace(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", container!=\"POD\", image!=\"\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", image!=\"\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) / sum(label_replace(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", container!=\"\", image!=\"\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set) / sum(label_replace(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", container != \"\", container != \"POD\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", container != \"\", container != \"POD\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    },
    {
     "expr": "sum(label_replace(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment-\\\\w+-\\\\w+$\", container != \"\", container != \"POD\"}, \"pod_set\", \"$1\", \"pod\", \"(.*)-\\\\w+-\\\\w+$\")) by (pod_set)"
    }
   ]
  },
  {
   "title": "K6s Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    { "expr": "k6_iterations{}", "legendFormat": "{{scenario}}" }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "k6_http_reqs",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by(scenario, error_code) (k6_http_reqs)",
     "legendFormat": "{{scenario}} - {{error_code}}"
    }
   ]
  },
  {
   "title": "Roundtrip time",
   "type": "timeseries",
   "description": "http_req_duration - Total time for the request -  how long the remote server took to process the request and respond, without the initial DNS lookup/connection times\n(http_req_sending + http_req_waiting + http_req_receiving)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    { "expr": "avg(k6_http_req_duration_avg)", "legendFormat": "Service  (Avg)" },
    {
     "expr": "sum by(scenario, expected_response) (k6_custom_highcpu_duration_avg)",
     "legendFormat": "{{scenario}}"
    },
    {
     "expr": "sum by(scenario, expected_response) (k6_custom_highmem_duration_avg)",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "k6_http_req_failed * k6_http_reqs",
     "legendFormat": "{{scenario}}_{{status}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Autoscaler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{}",
     "legendFormat": "Current Replicas {{horizontalpodautoscaler}}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{}",
     "legendFormat": "Max replicas"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}