apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-svc-mon
  namespace: monitoring
  labels:
    app: abt
spec:
  selector:
    matchLabels:
      app: abt
  endpoints:
  - port: metrics
    metricRelabelings:
    - sourceLabels: [namespace]
      regex: '(.*)'
      replacement: zerok-controller
      targetLabel: target_namespace