prometheus:
  url: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
  port: 9090
rules:
  default: false
  external:
  - seriesQuery: '{__name__=~"^some_metric_count$"}'
    resources:
      template: <<.Resource>>
    name:
      matches: ""
      as: "my_external_metric"
    metricsQuery: sum(k6_http_reqs{scenario="app_checkout"})
  custom:
  - metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
    name:
      as: http_req_per_second
    resources:
      overrides:
        ingress:
          resource: ingress
        namespace:
          resource: namespace
    seriesQuery: nginx_ingress_controller_requests
  - metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>) /
      sum(label_join(kube_deployment_status_replicas, "ingress", ",", "deployment"))
      by (<<.GroupBy>>)
    name:
      as: http_req_per_second_per_replica
    resources:
      overrides:
        ingress:
          resource: ingress
        namespace:
          resource: namespace
    seriesQuery: nginx_ingress_controller_requests