apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  labels:
    dep: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-hpa
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
