- op: replace
  path: /spec
  value:
    rules:
      - host: avin-demo-app-zerok-soak.getanton.com
        http:
          paths:
          - backend:
              service:
                name: svc-app-zerok-soak
                port: 
                  number: 80
            path: /.*
            pathType: Prefix